Instala as Bibliotecas

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\python314\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\python314\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python314\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\python314\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\python314\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install psycopg2

Requirement already satisfied: psycopg2 in c:\python314\lib\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Importar as Bibliotecas

In [4]:
import pandas as pd
pd.set_option("display.max_colwidth", 150)
pd.set_option("display.min_rows", 20)

from sqlalchemy import create_engine
from datetime import datetime, timedelta
import time

Definir função para buscar os Dados

In [5]:
def busca_titulos_tesouro_direto():
    url = 'https://www.tesourotransparente.gov.br/ckan/dataset/df56aa42-484a-4a59-8184-7676580c81e3/resource/796d2059-14e9-44e3-80c9-2d9e30b405c1/download/PrecoTaxaTesouroDireto.csv'
    df = pd.read_csv(url, sep=';', decimal=',')
    df['Data_Vencimento'] = pd.to_datetime(df['Data Vencimento'], dayfirst=True)
    df['Data_Base'] = pd.to_datetime(df['Data Base'], dayfirst=True)
    multi_indice = pd.MultiIndex.from_frame(df.iloc[:,:3])
    df = df.set_index(multi_indice).iloc[:, 3:]
    return df

Busca os títulos do Tesouro Direto

In [6]:
titulos = busca_titulos_tesouro_direto()

In [7]:
titulos

                                                                   Taxa Compra Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IPCA+ com Juros Semestrais     15/05/2035      16/05/2011               5.93
                                       15/08/2024      16/05/2011               6.18
Tesouro IPCA+                          15/08/2024      16/05/2011               6.09
                                       15/05/2015      16/05/2011               6.56
                                       15/05/2035      16/05/2011               5.68
Tesouro IGPM+ com Juros Semestrais     01/04/2021      16/05/2011               6.35
                                       01/07/2017      16/05/2011               6.37
                                       01/01/2031      16/05/2011               6.17
Tesouro Prefixado com Juros Semestrais 01/01/2012      16/05/2011              12.34
                                       01/01/2017      16/05/2011              12.56
...                                                                              ...
Tesouro IPCA+ com Juros Semestrais     15/08/2010      19/09/2007               7.03
                                       15/05/2011      19/09/2007               7.05
                                       15/08/2012      19/09/2007               7.03
                                       15/05/2015      19/09/2007               7.00
                                       15/05/2045      19/09/2007               6.28
                                       15/05/2017      19/09/2007               6.90
                                       15/08/2024      19/09/2007               6.52
                                       15/05/2035      19/09/2007               6.40
Tesouro IPCA+                          15/05/2015      19/09/2007               7.00
                                       15/08/2024      19/09/2007               6.36

                                                                   Taxa Venda Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IPCA+ com Juros Semestrais     15/05/2035      16/05/2011              6.03
                                       15/08/2024      16/05/2011              6.26
Tesouro IPCA+                          15/08/2024      16/05/2011              6.17
                                       15/05/2015      16/05/2011              6.60
                                       15/05/2035      16/05/2011              5.78
Tesouro IGPM+ com Juros Semestrais     01/04/2021      16/05/2011              6.41
                                       01/07/2017      16/05/2011              6.43
                                       01/01/2031      16/05/2011              6.25
Tesouro Prefixado com Juros Semestrais 01/01/2012      16/05/2011             12.38
                                       01/01/2017      16/05/2011             12.62
...                                                                             ...
Tesouro IPCA+ com Juros Semestrais     15/08/2010      19/09/2007              7.07
                                       15/05/2011      19/09/2007              7.09
                                       15/08/2012      19/09/2007              7.07
                                       15/05/2015      19/09/2007              7.06
                                       15/05/2045      19/09/2007              6.38
                                       15/05/2017      19/09/2007              6.96
                                       15/08/2024      19/09/2007              6.60
                                       15/05/2035      19/09/2007              6.50
Tesouro IPCA+                          15/05/2015      19/09/2007              7.06
                                       15/08/2024      19/09/2007              6.44

                                                                   PU Compra Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IPCA+ com Juros Semestrais     15/05/2035      16/05/2011          2066.71
                                       15/08/2024      16/05/2011          2044.95
Tesouro IPCA+                          15/08/2024      16/05/2011           936.25
                                       15/05/2015      16/05/2011          1585.98
                                       15/05/2035      16/05/2011           545.29
Tesouro IGPM+ com Juros Semestrais     01/04/2021      16/05/2011          2488.61
                                       01/07/2017      16/05/2011          2541.16
                                       01/01/2031      16/05/2011          4252.88
Tesouro Prefixado com Juros Semestrais 01/01/2012      16/05/2011          1022.65
                                       01/01/2017      16/05/2011           939.68
...                                                                            ...
Tesouro IPCA+ com Juros Semestrais     15/08/2010      19/09/2007          1633.80
                                       15/05/2011      19/09/2007          1648.34
                                       15/08/2012      19/09/2007          1608.67
                                       15/05/2015      19/09/2007          1607.57
                                       15/05/2045      19/09/2007          1639.42
                                       15/05/2017      19/09/2007          1601.34
                                       15/08/2024      19/09/2007          1593.24
                                       15/05/2035      19/09/2007          1620.74
Tesouro IPCA+                          15/05/2015      19/09/2007           994.40
                                       15/08/2024      19/09/2007           589.77

                                                                   PU Venda Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IPCA+ com Juros Semestrais     15/05/2035      16/05/2011         2041.33
                                       15/08/2024      16/05/2011         2030.88
Tesouro IPCA+                          15/08/2024      16/05/2011          926.97
                                       15/05/2015      16/05/2011         1583.61
                                       15/05/2035      16/05/2011          533.09
Tesouro IGPM+ com Juros Semestrais     01/04/2021      16/05/2011         2478.09
                                       01/07/2017      16/05/2011         2533.87
                                       01/01/2031      16/05/2011         4220.83
Tesouro Prefixado com Juros Semestrais 01/01/2012      16/05/2011         1022.43
                                       01/01/2017      16/05/2011          937.57
...                                                                           ...
Tesouro IPCA+ com Juros Semestrais     15/08/2010      19/09/2007         1632.16
                                       15/05/2011      19/09/2007         1646.35
                                       15/08/2012      19/09/2007         1606.10
                                       15/05/2015      19/09/2007         1602.11
                                       15/05/2045      19/09/2007         1616.93
                                       15/05/2017      19/09/2007         1594.87
                                       15/08/2024      19/09/2007         1580.57
                                       15/05/2035      19/09/2007         1600.72
Tesouro IPCA+                          15/05/2015      19/09/2007          990.15
                                       15/08/2024      19/09/2007          582.35

                                                                   PU Base Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IPCA+ com Juros Semestrais     15/05/2035      16/05/2011        2040.53
                                       15/08/2024      16/05/2011        2030.07
Tesouro IPCA+                          15/08/2024      16/05/2011         926.61
                                       15/05/2015      16/05/2011        1582.96
                                       15/05/2035      16/05/2011         532.89
Tesouro IGPM+ com Juros Semestrais     01/04/2021      16/05/2011        2476.97
                                       01/07/2017      16/05/2011        2532.72
                                       01/01/2031      16/05/2011        4218.94
Tesouro Prefixado com Juros Semestrais 01/01/2012      16/05/2011        1021.96
                                       01/01/2017      16/05/2011         937.13
...                                                                          ...
Tesouro IPCA+ com Juros Semestrais     15/08/2010      19/09/2007        1631.53
                                       15/05/2011      19/09/2007        1645.71
                                       15/08/2012      19/09/2007        1605.48
                                       15/05/2015      19/09/2007        1601.49
                                       15/05/2045      19/09/2007        1616.34
                                       15/05/2017      19/09/2007        1594.25
                                       15/08/2024      19/09/2007        1579.99
                                       15/05/2035      19/09/2007        1600.13
Tesouro IPCA+                          15/05/2015      19/09/2007         989.77
                                       15/08/2024      19/09/2007         582.14

                                                                  Data_Vencimento  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IPCA+ com Juros Semestrais     15/05/2035      16/05/2011      2035-05-15
                                       15/08/2024      16/05/2011      2024-08-15
Tesouro IPCA+                          15/08/2024      16/05/2011      2024-08-15
                                       15/05/2015      16/05/2011      2015-05-15
                                       15/05/2035      16/05/2011      2035-05-15
Tesouro IGPM+ com Juros Semestrais     01/04/2021      16/05/2011      2021-04-01
                                       01/07/2017      16/05/2011      2017-07-01
                                       01/01/2031      16/05/2011      2031-01-01
Tesouro Prefixado com Juros Semestrais 01/01/2012      16/05/2011      2012-01-01
                                       01/01/2017      16/05/2011      2017-01-01
...                                                                           ...
Tesouro IPCA+ com Juros Semestrais     15/08/2010      19/09/2007      2010-08-15
                                       15/05/2011      19/09/2007      2011-05-15
                                       15/08/2012      19/09/2007      2012-08-15
                                       15/05/2015      19/09/2007      2015-05-15
                                       15/05/2045      19/09/2007      2045-05-15
                                       15/05/2017      19/09/2007      2017-05-15
                                       15/08/2024      19/09/2007      2024-08-15
                                       15/05/2035      19/09/2007      2035-05-15
Tesouro IPCA+                          15/05/2015      19/09/2007      2015-05-15
                                       15/08/2024      19/09/2007      2024-08-15

                                                                   Data_Base
Tipo Titulo                            Data Vencimento Data Base
Tesouro IPCA+ com Juros Semestrais     15/05/2035      16/05/2011 2011-05-16
                                       15/08/2024      16/05/2011 2011-05-16
Tesouro IPCA+                          15/08/2024      16/05/2011 2011-05-16
                                       15/05/2015      16/05/2011 2011-05-16
                                       15/05/2035      16/05/2011 2011-05-16
Tesouro IGPM+ com Juros Semestrais     01/04/2021      16/05/2011 2011-05-16
                                       01/07/2017      16/05/2011 2011-05-16
                                       01/01/2031      16/05/2011 2011-05-16
Tesouro Prefixado com Juros Semestrais 01/01/2012      16/05/2011 2011-05-16
                                       01/01/2017      16/05/2011 2011-05-16
...                                                                      ...
Tesouro IPCA+ com Juros Semestrais     15/08/2010      19/09/2007 2007-09-19
                                       15/05/2011      19/09/2007 2007-09-19
                                       15/08/2012      19/09/2007 2007-09-19
                                       15/05/2015      19/09/2007 2007-09-19
                                       15/05/2045      19/09/2007 2007-09-19
                                       15/05/2017      19/09/2007 2007-09-19
                                       15/08/2024      19/09/2007 2007-09-19
                                       15/05/2035      19/09/2007 2007-09-19
Tesouro IPCA+                          15/05/2015      19/09/2007 2007-09-19
                                       15/08/2024      19/09/2007 2007-09-19

[167123 rows x 7 columns]

Busca somente os Préfixados

In [8]:
prefixado = titulos.loc[('Tesouro Prefixado')]
prefixado['Tipo'] = "PRE-FIXADOS"

C:\Users\lab-ssd\AppData\Local\Temp\ipykernel_31980\2914005242.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefixado['Tipo'] = "PRE-FIXADOS"

In [9]:
prefixado

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
01/07/2011      13/05/2011              12.06             12.09
01/01/2012      13/05/2011              12.36             12.40
01/01/2014      13/05/2011              12.58             12.64
01/01/2015      13/05/2011              12.63             12.69
01/01/2013      13/05/2011              12.58             12.63
01/07/2011      12/05/2011              12.07             12.10
01/01/2012      12/05/2011              12.34             12.38
01/01/2013      12/05/2011              12.59             12.64
01/01/2014      12/05/2011              12.57             12.63
01/01/2015      12/05/2011              12.63             12.69
...                                       ...               ...
01/10/2009      20/09/2007              11.52             11.58
01/10/2007      20/09/2007              11.15             11.18
                19/09/2007              11.16             11.19
01/01/2008      19/09/2007              11.09             11.12
01/04/2008      19/09/2007              11.14             11.18
01/07/2008      19/09/2007              11.22             11.26
01/10/2008      19/09/2007              11.36             11.40
01/01/2009      19/09/2007              11.44             11.48
01/07/2009      19/09/2007              11.58             11.63
01/10/2009      19/09/2007              11.60             11.66

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
01/07/2011      13/05/2011           985.19          985.16         984.71
01/01/2012      13/05/2011           928.67          928.46         928.03
01/01/2014      13/05/2011           731.81          730.79         730.44
01/01/2015      13/05/2011           648.68          647.43         647.12
01/01/2013      13/05/2011           824.26          823.67         823.28
01/07/2011      12/05/2011           984.74          984.70         984.26
01/01/2012      12/05/2011           928.35          928.14         927.71
01/01/2013      12/05/2011           823.76          823.16         822.77
01/01/2014      12/05/2011           731.64          730.61         730.27
01/01/2015      12/05/2011           648.38          647.12         646.81
...                                     ...             ...            ...
01/10/2009      20/09/2007           802.33          801.46         801.11
01/10/2007      20/09/2007           997.48          997.47         997.06
                19/09/2007           997.06          997.05         996.63
01/01/2008      19/09/2007           971.61          971.54         971.13
01/04/2008      19/09/2007           946.97          946.79         946.39
01/07/2008      19/09/2007           922.17          921.92         921.53
01/10/2008      19/09/2007           895.69          895.36         894.97
01/01/2009      19/09/2007           870.37          869.97         869.59
01/07/2009      19/09/2007           824.07          823.42         823.06
01/10/2009      19/09/2007           800.82          799.95         799.60

                           Data_Vencimento  Data_Base         Tipo
Data Vencimento Data Base
01/07/2011      13/05/2011      2011-07-01 2011-05-13  PRE-FIXADOS
01/01/2012      13/05/2011      2012-01-01 2011-05-13  PRE-FIXADOS
01/01/2014      13/05/2011      2014-01-01 2011-05-13  PRE-FIXADOS
01/01/2015      13/05/2011      2015-01-01 2011-05-13  PRE-FIXADOS
01/01/2013      13/05/2011      2013-01-01 2011-05-13  PRE-FIXADOS
01/07/2011      12/05/2011      2011-07-01 2011-05-12  PRE-FIXADOS
01/01/2012      12/05/2011      2012-01-01 2011-05-12  PRE-FIXADOS
01/01/2013      12/05/2011      2013-01-01 2011-05-12  PRE-FIXADOS
01/01/2014      12/05/2011      2014-01-01 2011-05-12  PRE-FIXADOS
01/01/2015      12/05/2011      2015-01-01 2011-05-12  PRE-FIXADOS
...                                    ...        ...          ...
01/10/2009      20/09/2007      2009-10-01 2007-09-20  PRE-FIXADOS
01/10/2007      20/09/2007      2007-10-01 2007-09-20  PRE-FIXADOS
                19/09/2007      2007-10-01 2007-09-19  PRE-FIXADOS
01/01/2008      19/09/2007      2008-01-01 2007-09-19  PRE-FIXADOS
01/04/2008      19/09/2007      2008-04-01 2007-09-19  PRE-FIXADOS
01/07/2008      19/09/2007      2008-07-01 2007-09-19  PRE-FIXADOS
01/10/2008      19/09/2007      2008-10-01 2007-09-19  PRE-FIXADOS
01/01/2009      19/09/2007      2009-01-01 2007-09-19  PRE-FIXADOS
01/07/2009      19/09/2007      2009-07-01 2007-09-19  PRE-FIXADOS
01/10/2009      19/09/2007      2009-10-01 2007-09-19  PRE-FIXADOS

[27350 rows x 8 columns]

In [10]:
for i, row in prefixado.iterrows():
    ifor_val = datetime.now() - timedelta(hours=1, minutes=0)
    prefixado.at[i,'dt_update'] = ifor_val
    time.sleep(1/10000)

C:\Users\lab-ssd\AppData\Local\Temp\ipykernel_31980\913561871.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefixado.at[i,'dt_update'] = ifor_val

In [11]:
prefixado

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
01/07/2011      13/05/2011              12.06             12.09
01/01/2012      13/05/2011              12.36             12.40
01/01/2014      13/05/2011              12.58             12.64
01/01/2015      13/05/2011              12.63             12.69
01/01/2013      13/05/2011              12.58             12.63
01/07/2011      12/05/2011              12.07             12.10
01/01/2012      12/05/2011              12.34             12.38
01/01/2013      12/05/2011              12.59             12.64
01/01/2014      12/05/2011              12.57             12.63
01/01/2015      12/05/2011              12.63             12.69
...                                       ...               ...
01/10/2009      20/09/2007              11.52             11.58
01/10/2007      20/09/2007              11.15             11.18
                19/09/2007              11.16             11.19
01/01/2008      19/09/2007              11.09             11.12
01/04/2008      19/09/2007              11.14             11.18
01/07/2008      19/09/2007              11.22             11.26
01/10/2008      19/09/2007              11.36             11.40
01/01/2009      19/09/2007              11.44             11.48
01/07/2009      19/09/2007              11.58             11.63
01/10/2009      19/09/2007              11.60             11.66

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
01/07/2011      13/05/2011           985.19          985.16         984.71
01/01/2012      13/05/2011           928.67          928.46         928.03
01/01/2014      13/05/2011           731.81          730.79         730.44
01/01/2015      13/05/2011           648.68          647.43         647.12
01/01/2013      13/05/2011           824.26          823.67         823.28
01/07/2011      12/05/2011           984.74          984.70         984.26
01/01/2012      12/05/2011           928.35          928.14         927.71
01/01/2013      12/05/2011           823.76          823.16         822.77
01/01/2014      12/05/2011           731.64          730.61         730.27
01/01/2015      12/05/2011           648.38          647.12         646.81
...                                     ...             ...            ...
01/10/2009      20/09/2007           802.33          801.46         801.11
01/10/2007      20/09/2007           997.48          997.47         997.06
                19/09/2007           997.06          997.05         996.63
01/01/2008      19/09/2007           971.61          971.54         971.13
01/04/2008      19/09/2007           946.97          946.79         946.39
01/07/2008      19/09/2007           922.17          921.92         921.53
01/10/2008      19/09/2007           895.69          895.36         894.97
01/01/2009      19/09/2007           870.37          869.97         869.59
01/07/2009      19/09/2007           824.07          823.42         823.06
01/10/2009      19/09/2007           800.82          799.95         799.60

                           Data_Vencimento  Data_Base         Tipo  \
Data Vencimento Data Base
01/07/2011      13/05/2011      2011-07-01 2011-05-13  PRE-FIXADOS
01/01/2012      13/05/2011      2012-01-01 2011-05-13  PRE-FIXADOS
01/01/2014      13/05/2011      2014-01-01 2011-05-13  PRE-FIXADOS
01/01/2015      13/05/2011      2015-01-01 2011-05-13  PRE-FIXADOS
01/01/2013      13/05/2011      2013-01-01 2011-05-13  PRE-FIXADOS
01/07/2011      12/05/2011      2011-07-01 2011-05-12  PRE-FIXADOS
01/01/2012      12/05/2011      2012-01-01 2011-05-12  PRE-FIXADOS
01/01/2013      12/05/2011      2013-01-01 2011-05-12  PRE-FIXADOS
01/01/2014      12/05/2011      2014-01-01 2011-05-12  PRE-FIXADOS
01/01/2015      12/05/2011      2015-01-01 2011-05-12  PRE-FIXADOS
...                                    ...        ...          ...
01/10/2009      20/09/2007      2009-10-01 2007-09-20  PRE-FIXADOS
01/10/2007      20/09/2007      2007-10-01 2007-09-20  PRE-FIXADOS
                19/09/2007      2007-10-01 2007-09-19  PRE-FIXADOS
01/01/2008      19/09/2007      2008-01-01 2007-09-19  PRE-FIXADOS
01/04/2008      19/09/2007      2008-04-01 2007-09-19  PRE-FIXADOS
01/07/2008      19/09/2007      2008-07-01 2007-09-19  PRE-FIXADOS
01/10/2008      19/09/2007      2008-10-01 2007-09-19  PRE-FIXADOS
01/01/2009      19/09/2007      2009-01-01 2007-09-19  PRE-FIXADOS
01/07/2009      19/09/2007      2009-07-01 2007-09-19  PRE-FIXADOS
01/10/2009      19/09/2007      2009-10-01 2007-09-19  PRE-FIXADOS

                                            dt_update
Data Vencimento Data Base
01/07/2011      13/05/2011 2026-02-05 14:15:30.446034
01/01/2012      13/05/2011 2026-02-05 14:15:30.449450
01/01/2014      13/05/2011 2026-02-05 14:15:30.450453
01/01/2015      13/05/2011 2026-02-05 14:15:30.451544
01/01/2013      13/05/2011 2026-02-05 14:15:30.452442
01/07/2011      12/05/2011 2026-02-05 14:15:30.453439
01/01/2012      12/05/2011 2026-02-05 14:15:30.454438
01/01/2013      12/05/2011 2026-02-05 14:15:30.455444
01/01/2014      12/05/2011 2026-02-05 14:15:30.456438
01/01/2015      12/05/2011 2026-02-05 14:15:30.457457
...                                               ...
01/10/2009      20/09/2007 2026-02-05 14:15:52.162971
01/10/2007      20/09/2007 2026-02-05 14:15:52.163982
                19/09/2007 2026-02-05 14:15:52.165334
01/01/2008      19/09/2007 2026-02-05 14:15:52.165969
01/04/2008      19/09/2007 2026-02-05 14:15:52.170693
01/07/2008      19/09/2007 2026-02-05 14:15:52.172008
01/10/2008      19/09/2007 2026-02-05 14:15:52.172988
01/01/2009      19/09/2007 2026-02-05 14:15:52.174003
01/07/2009      19/09/2007 2026-02-05 14:15:52.174949
01/10/2009      19/09/2007 2026-02-05 14:15:52.175952

[27350 rows x 9 columns]

Busca os IPCAs

In [12]:
ipca = titulos.loc[('Tesouro IPCA+')]
ipca['Tipo'] = "IPCA"

C:\Users\lab-ssd\AppData\Local\Temp\ipykernel_31980\3738600803.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca['Tipo'] = "IPCA"

In [13]:
for i, row in ipca.iterrows():
    ifor_val = datetime.now() - timedelta(hours=1, minutes=0)
    ipca.at[i,'dt_update'] = ifor_val
    time.sleep(1/10000)

C:\Users\lab-ssd\AppData\Local\Temp\ipykernel_31980\3161604202.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca.at[i,'dt_update'] = ifor_val

In [14]:
ipca

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
15/08/2024      16/05/2011               6.09              6.17
15/05/2015      16/05/2011               6.56              6.60
15/05/2035      16/05/2011               5.68              5.78
15/05/2015      13/05/2011               6.61              6.65
15/08/2024      13/05/2011               6.12              6.20
15/05/2035      13/05/2011               5.69              5.79
15/05/2015      12/05/2011               6.61              6.65
15/08/2024      12/05/2011               6.12              6.20
15/05/2035      12/05/2011               5.70              5.80
                11/05/2011               5.70              5.80
...                                       ...               ...
15/05/2015      20/11/2007               7.38              7.44
15/08/2024      20/11/2007               6.74              6.82
                19/11/2007               6.74              6.82
15/05/2015      19/11/2007               7.35              7.41
                21/09/2007               6.84              6.90
15/08/2024      21/09/2007               6.39              6.47
                20/09/2007               6.35              6.43
15/05/2015      20/09/2007               6.89              6.95
                19/09/2007               7.00              7.06
15/08/2024      19/09/2007               6.36              6.44

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
15/08/2024      16/05/2011           936.25          926.97         926.61
15/05/2015      16/05/2011          1585.98         1583.61        1582.96
15/05/2035      16/05/2011           545.29          533.09         532.89
15/05/2015      13/05/2011          1582.36         1579.99        1578.84
15/08/2024      13/05/2011           932.39          923.15         922.50
15/05/2035      13/05/2011           543.85          531.69         531.32
15/05/2015      12/05/2011          1580.90         1578.53        1577.73
15/08/2024      12/05/2011           931.55          922.32         921.86
15/05/2035      12/05/2011           542.14          530.01         529.76
                11/05/2011           541.88          529.76         529.50
...                                     ...             ...            ...
15/05/2015      20/11/2007           983.85          979.76         979.38
15/08/2024      20/11/2007           564.02          557.01         556.81
                19/11/2007           563.82          556.81         556.61
15/05/2015      19/11/2007           985.53          981.43         981.05
                21/09/2007          1006.81         1002.51        1001.89
15/08/2024      21/09/2007           587.54          580.16         579.81
                20/09/2007           590.92          583.49         583.28
15/05/2015      20/09/2007          1002.61          998.33         997.95
                19/09/2007           994.40          990.15         989.77
15/08/2024      19/09/2007           589.77          582.35         582.14

                           Data_Vencimento  Data_Base  Tipo  \
Data Vencimento Data Base
15/08/2024      16/05/2011      2024-08-15 2011-05-16  IPCA
15/05/2015      16/05/2011      2015-05-15 2011-05-16  IPCA
15/05/2035      16/05/2011      2035-05-15 2011-05-16  IPCA
15/05/2015      13/05/2011      2015-05-15 2011-05-13  IPCA
15/08/2024      13/05/2011      2024-08-15 2011-05-13  IPCA
15/05/2035      13/05/2011      2035-05-15 2011-05-13  IPCA
15/05/2015      12/05/2011      2015-05-15 2011-05-12  IPCA
15/08/2024      12/05/2011      2024-08-15 2011-05-12  IPCA
15/05/2035      12/05/2011      2035-05-15 2011-05-12  IPCA
                11/05/2011      2035-05-15 2011-05-11  IPCA
...                                    ...        ...   ...
15/05/2015      20/11/2007      2015-05-15 2007-11-20  IPCA
15/08/2024      20/11/2007      2024-08-15 2007-11-20  IPCA
                19/11/2007      2024-08-15 2007-11-19  IPCA
15/05/2015      19/11/2007      2015-05-15 2007-11-19  IPCA
                21/09/2007      2015-05-15 2007-09-21  IPCA
15/08/2024      21/09/2007      2024-08-15 2007-09-21  IPCA
                20/09/2007      2024-08-15 2007-09-20  IPCA
15/05/2015      20/09/2007      2015-05-15 2007-09-20  IPCA
                19/09/2007      2015-05-15 2007-09-19  IPCA
15/08/2024      19/09/2007      2024-08-15 2007-09-19  IPCA

                                            dt_update
Data Vencimento Data Base
15/08/2024      16/05/2011 2026-02-05 14:15:52.271698
15/05/2015      16/05/2011 2026-02-05 14:15:52.275759
15/05/2035      16/05/2011 2026-02-05 14:15:52.276728
15/05/2015      13/05/2011 2026-02-05 14:15:52.277700
15/08/2024      13/05/2011 2026-02-05 14:15:52.278806
15/05/2035      13/05/2011 2026-02-05 14:15:52.279832
15/05/2015      12/05/2011 2026-02-05 14:15:52.280867
15/08/2024      12/05/2011 2026-02-05 14:15:52.281782
15/05/2035      12/05/2011 2026-02-05 14:15:52.282745
                11/05/2011 2026-02-05 14:15:52.283736
...                                               ...
15/05/2015      20/11/2007 2026-02-05 14:16:06.544923
15/08/2024      20/11/2007 2026-02-05 14:16:06.545959
                19/11/2007 2026-02-05 14:16:06.546978
15/05/2015      19/11/2007 2026-02-05 14:16:06.547975
                21/09/2007 2026-02-05 14:16:06.548933
15/08/2024      21/09/2007 2026-02-05 14:16:06.549936
                20/09/2007 2026-02-05 14:16:06.550917
15/05/2015      20/09/2007 2026-02-05 14:16:06.551967
                19/09/2007 2026-02-05 14:16:06.553009
15/08/2024      19/09/2007 2026-02-05 14:16:06.553932

[17773 rows x 9 columns]

In [15]:
#frames = [prefixado, ipca]
#todos = pd.concat(frames)
ipca = ipca.rename(columns={"Data Vencimento": "DataVencimento", "Data Base": "Data_Base", "Taxa Compra Manha": "CompraManha", "Taxa Venda Manha": "VendaManha", "PU Compra Manha": "PUCompraManha", "PU Venda Manha": "PUVendaManha",  "PU Base Manha": "PUBaseManha"})
prefixado = prefixado.rename(columns={"Data Vencimento": "DataVencimento", "Data Base": "Data_Base", "Taxa Compra Manha": "CompraManha", "Taxa Venda Manha": "VendaManha", "PU Compra Manha": "PUCompraManha", "PU Venda Manha": "PUVendaManha",  "PU Base Manha": "PUBaseManha"})

In [16]:
ipca

                            CompraManha  VendaManha  PUCompraManha  \
Data Vencimento Data Base
15/08/2024      16/05/2011         6.09        6.17         936.25
15/05/2015      16/05/2011         6.56        6.60        1585.98
15/05/2035      16/05/2011         5.68        5.78         545.29
15/05/2015      13/05/2011         6.61        6.65        1582.36
15/08/2024      13/05/2011         6.12        6.20         932.39
15/05/2035      13/05/2011         5.69        5.79         543.85
15/05/2015      12/05/2011         6.61        6.65        1580.90
15/08/2024      12/05/2011         6.12        6.20         931.55
15/05/2035      12/05/2011         5.70        5.80         542.14
                11/05/2011         5.70        5.80         541.88
...                                 ...         ...            ...
15/05/2015      20/11/2007         7.38        7.44         983.85
15/08/2024      20/11/2007         6.74        6.82         564.02
                19/11/2007         6.74        6.82         563.82
15/05/2015      19/11/2007         7.35        7.41         985.53
                21/09/2007         6.84        6.90        1006.81
15/08/2024      21/09/2007         6.39        6.47         587.54
                20/09/2007         6.35        6.43         590.92
15/05/2015      20/09/2007         6.89        6.95        1002.61
                19/09/2007         7.00        7.06         994.40
15/08/2024      19/09/2007         6.36        6.44         589.77

                            PUVendaManha  PUBaseManha Data_Vencimento  \
Data Vencimento Data Base
15/08/2024      16/05/2011        926.97       926.61      2024-08-15
15/05/2015      16/05/2011       1583.61      1582.96      2015-05-15
15/05/2035      16/05/2011        533.09       532.89      2035-05-15
15/05/2015      13/05/2011       1579.99      1578.84      2015-05-15
15/08/2024      13/05/2011        923.15       922.50      2024-08-15
15/05/2035      13/05/2011        531.69       531.32      2035-05-15
15/05/2015      12/05/2011       1578.53      1577.73      2015-05-15
15/08/2024      12/05/2011        922.32       921.86      2024-08-15
15/05/2035      12/05/2011        530.01       529.76      2035-05-15
                11/05/2011        529.76       529.50      2035-05-15
...                                  ...          ...             ...
15/05/2015      20/11/2007        979.76       979.38      2015-05-15
15/08/2024      20/11/2007        557.01       556.81      2024-08-15
                19/11/2007        556.81       556.61      2024-08-15
15/05/2015      19/11/2007        981.43       981.05      2015-05-15
                21/09/2007       1002.51      1001.89      2015-05-15
15/08/2024      21/09/2007        580.16       579.81      2024-08-15
                20/09/2007        583.49       583.28      2024-08-15
15/05/2015      20/09/2007        998.33       997.95      2015-05-15
                19/09/2007        990.15       989.77      2015-05-15
15/08/2024      19/09/2007        582.35       582.14      2024-08-15

                            Data_Base  Tipo                  dt_update
Data Vencimento Data Base
15/08/2024      16/05/2011 2011-05-16  IPCA 2026-02-05 14:15:52.271698
15/05/2015      16/05/2011 2011-05-16  IPCA 2026-02-05 14:15:52.275759
15/05/2035      16/05/2011 2011-05-16  IPCA 2026-02-05 14:15:52.276728
15/05/2015      13/05/2011 2011-05-13  IPCA 2026-02-05 14:15:52.277700
15/08/2024      13/05/2011 2011-05-13  IPCA 2026-02-05 14:15:52.278806
15/05/2035      13/05/2011 2011-05-13  IPCA 2026-02-05 14:15:52.279832
15/05/2015      12/05/2011 2011-05-12  IPCA 2026-02-05 14:15:52.280867
15/08/2024      12/05/2011 2011-05-12  IPCA 2026-02-05 14:15:52.281782
15/05/2035      12/05/2011 2011-05-12  IPCA 2026-02-05 14:15:52.282745
                11/05/2011 2011-05-11  IPCA 2026-02-05 14:15:52.283736
...                               ...   ...                        ...
15/05/2015      20/11/2007 2007-11-20  IPCA 2026-02-05 14:16:06.544923
15/08/2024      20/11/2007 2007-11-20  IPCA 2026-02-05 14:16:06.545959
                19/11/2007 2007-11-19  IPCA 2026-02-05 14:16:06.546978
15/05/2015      19/11/2007 2007-11-19  IPCA 2026-02-05 14:16:06.547975
                21/09/2007 2007-09-21  IPCA 2026-02-05 14:16:06.548933
15/08/2024      21/09/2007 2007-09-21  IPCA 2026-02-05 14:16:06.549936
                20/09/2007 2007-09-20  IPCA 2026-02-05 14:16:06.550917
15/05/2015      20/09/2007 2007-09-20  IPCA 2026-02-05 14:16:06.551967
                19/09/2007 2007-09-19  IPCA 2026-02-05 14:16:06.553009
15/08/2024      19/09/2007 2007-09-19  IPCA 2026-02-05 14:16:06.553932

[17773 rows x 9 columns]

Grava os dados no Banco de Dados

In [17]:
connection_string = "postgresql://postgres:postgres@localhost:5432/postgres"

In [18]:
engine = create_engine(connection_string)

In [19]:
ipca.to_sql("dadostesouroipca", con=engine, if_exists="append", index=False)
prefixado.to_sql("dadostesouropre", con=engine, if_exists="append", index=False)

350